file(MAKE_DIRECTORY "${TEST_BINARY_DIR}")

if(NOT CONTRACT_CXX_STANDARD)
    set(CONTRACT_CXX_STANDARD 17)
endif()

if(NOT DEFINED CONTRACT_ENABLE_SPAN)
    set(CONTRACT_ENABLE_SPAN 0)
endif()

execute_process(
    COMMAND
        "${CONTRACT_CXX_COMPILER}"
        "-std=c++${CONTRACT_CXX_STANDARD}"
        "-DCONTRACT_ENABLE_SPAN=${CONTRACT_ENABLE_SPAN}"
        "-I${CONTRACT_INCLUDE_DIR}"
        "-c"
        "${TEST_SOURCE}"
        "-o"
        "${TEST_BINARY_DIR}/test.o"
    RESULT_VARIABLE CONTRACT_COMPILE_RESULT
    OUTPUT_VARIABLE CONTRACT_COMPILE_OUTPUT
    ERROR_VARIABLE CONTRACT_COMPILE_ERROR
)

if(CONTRACT_COMPILE_RESULT EQUAL 0)
    message(FATAL_ERROR "Expected ${TEST_SOURCE} to fail compilation")
endif()
