name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: ${{ matrix.compiler }} / ${{ matrix.build_type }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang++]
        build_type: [Debug]

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          -DCONTRACT_BUILD_BENCHMARKS=OFF
          -DCONTRACT_BUILD_EXAMPLES=ON
          -DCONTRACT_BUILD_TESTS=ON
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure
